import AboutSection from '@/components/pages/AboutSection'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "NaufalRF Portfolio | About",
  description: "Generated by create next app",
};


const AboutPage = () => {
  return (
    <AboutSection />
  )
}

export default AboutPage