import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "NaufalRF Portfolio | Blogs",
  description: "Generated by create next app",
};


const BlogPage = () => {
  return (
    <div>BlogPage</div>
  )
}

export default BlogPage