import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "NaufalRF Portfolio | Projects",
  description: "Generated by create next app",
};


const ProjectPage = () => {
  return (
    <div>ProjectPage</div>
  )
}

export default ProjectPage