import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "NaufalRF Portfolio | Contact",
  description: "Generated by create next app",
};


const ContactPage = () => {
  return (
    <div>ContactPage</div>
  )
}

export default ContactPage